platform:ios,'7.0'
pod 'Reachability','~>3.0.0'
pod 'AFNetworking', '~> 2.5.1'
pod 'UMengSocial', '~> 4.2.3'
pod 'Flurry-iOS-SDK', '~> 7.3.0'
pod 'SDCycleScrollView', '~>1.3'
pod 'SDWebImage'
pod 'Mantle', '~> 2.0.6'
